// Vocabulary words from Word Wizard Vocabulary List (3rd-5th Grade)
// Each word includes: word, type, and definition

const vocabularyWords = [
    { word: "Abbreviate", type: "v.", definition: "To shorten (a word or phrase) by omitting letters, substituting shorter forms, etc., so that the shortened form can represent the whole word or phrase." },
    { word: "Ability", type: "n.", definition: "Power or capacity to do or act physically, mentally, legally, morally, financially, etc." },
    { word: "Abrasive", type: "adj.", definition: "Wearing, grinding or rubbing away by friction; rough." },
    { word: "Absence", type: "n.", definition: "State of being away or not being present." },
    { word: "Accidental", type: "adj.", definition: "Happening by chance or accident; not planned; unexpected." },
    { word: "Accomplice", type: "n.", definition: "One that participates with another in a crime either as principal or accessory." },
    { word: "Accurate", type: "adj.", definition: "Correct, exact, precise." },
    { word: "Acre", type: "n.", definition: "A unit of area in the U.S. Customary System, used in land and sea floor measurement and equal to 160." },
    { word: "Adequate", type: "adj.", definition: "Sufficient to satisfy a requirement or meet a need." },
    { word: "Admire", type: "v.", definition: "To regard with wonder, pleasure, or approval." },
    { word: "Adolescence", type: "n.", definition: "The period of physical and psychological development from the onset of puberty to maturity." },
    { word: "Advantageous", type: "adj.", definition: "Affording advantage; beneficial." },
    { word: "Aggravate", type: "v.", definition: "To make worse, more serious, or more severe." },
    { word: "Alliance", type: "n.", definition: "Union or connection especially between families, states, parties, or individuals." },
    { word: "Aloof", type: "adj.", definition: "Distant physically or emotionally; reserved and remote." },
    { word: "Altogether", type: "adv.", definition: "Wholly, completely, thoroughly." },
    { word: "Amateur", type: "n.", definition: "A person who engages in a study, sport, or other activity for pleasure rather than for financial benefit or professional reasons." },
    { word: "Ambivalent", type: "adj.", definition: "Characterized by a mixture of opposite feelings or attitudes." },
    { word: "Amnesia", type: "n.", definition: "Partial or total loss of memory, usually resulting from shock, psychological disturbance, brain injury, or illness." },
    { word: "Amphibian", type: "n.", definition: "An animal or plant accustomed or adapted to life both on land and in the water." },
    { word: "Anomaly", type: "n.", definition: "Deviation or departure from the normal or common order, form, or rule." },
    { word: "Anxiety", type: "n.", definition: "A state of uneasiness and apprehension, as about future uncertainties." },
    { word: "Appetite", type: "n.", definition: "An instinctive physical desire, especially one for food or drink." },
    { word: "Apprentice", type: "n.", definition: "One who learns a trade, art, or craft by practical experience under skilled workers." },
    { word: "Appropriate", type: "adj.", definition: "Suitable for a particular person, condition, occasion, or place; fitting." },
    { word: "Arbiter", type: "n.", definition: "One chosen or appointed to judge or decide a disputed issue; an arbitrator." },
    { word: "Arrogance", type: "n.", definition: "The state or quality of being arrogant; overbearing pride." },
    { word: "Artificial", type: "adj.", definition: "Made by humans; produced rather than natural." },
    { word: "Audience", type: "n.", definition: "Those attending a stage or film production or viewing a televised program." },
    { word: "Augment", type: "v.", definition: "To make (something already developed or well under way) greater, as in size, extent, or quantity." },
    { word: "Author", type: "n.", definition: "The writer of a book, article, or other text." },
    { word: "Avalanche", type: "n.", definition: "A large mass of snow, ice, earth, rock, or other material in swift motion down a mountainside." },
    { word: "Bachelor", type: "n.", definition: "An unmarried man of marriageable age." },
    { word: "Ballerina", type: "n.", definition: "A female ballet dancer." },
    { word: "Banquet", type: "n.", definition: "A lavish meal; feast." },
    { word: "Barbaric", type: "adj.", definition: "Characteristic of one who lacks refinement, gentleness, learning, or artistic or literary culture." },
    { word: "Barracks", type: "n.", definition: "An often permanent building or set of buildings used, especially for lodging soldiers." },
    { word: "Belligerent", type: "adj.", definition: "Inclined or eager to fight; hostile or aggressive." },
    { word: "Benediction", type: "n.", definition: "An expression or utterance of blessing or good wishes." },
    { word: "Beret", type: "n.", definition: "A soft flat visorless cap of woolen material originally worn by Basque peasants." },
    { word: "Billionaire", type: "n.", definition: "A person whose wealth amounts to at least a billion dollars, pounds, or the equivalent in other currency." },
    { word: "Binoculars", type: "n.", definition: "A handheld optical instrument composed of two telescopes and a focusing device and usually having prisms to increase magnifying ability." },
    { word: "Boisterous", type: "adj.", definition: "Rough and stormy; violent." },
    { word: "Boundary", type: "n.", definition: "Something that indicates bounds or limits; a limiting or bounding line." },
    { word: "Boycott", type: "v.", definition: "To combine against (a person, employer, a group of persons, or a nation) in a policy of suspension of dealings." },
    { word: "Briefcase", type: "n.", definition: "A portable, often flat case with a handle, used for carrying papers or books." },
    { word: "Brilliant", type: "adj.", definition: "Marked by unusual and impressive intellectual acuteness." },
    { word: "Bureaucracy", type: "n.", definition: "A system of administration marked by lack of initiative and flexibility, by indifference to human needs or public opinion, and by a tendency to defer decisions to superiors or to impede action with red tape." },
    { word: "Cafeteria", type: "n.", definition: "A self-service restaurant or lunchroom." },
    { word: "Calculator", type: "n.", definition: "A device used for computing amounts." },
    { word: "Camera", type: "n.", definition: "An apparatus for taking photographs." },
    { word: "Camouflage", type: "n.", definition: "A disguise; behavior adopted or designed to deceive or hide." },
    { word: "Candidacy", type: "n.", definition: "The quality or state of being one that is likely or worthy to gain a post, position, or distinction." },
    { word: "Canopy", type: "n.", definition: "A covering, usually of fabric, supported on poles or suspended above a bed, throne, exalted personage, or sacred object." },
    { word: "Canteen", type: "n.", definition: "A small container used especially by soldiers and hikers for carrying water or other liquids." },
    { word: "Capital", type: "adj.", definition: "Highly meritorious; most enjoyable." },
    { word: "Casserole", type: "n.", definition: "A dish usually having a cover and a handle and in which food may be baked and served." },
    { word: "Catastrophe", type: "n.", definition: "A sudden, terrible calamity; disaster." },
    { word: "Character", type: "n.", definition: "Personality as represented or realized in fiction or drama." },
    { word: "Chauffeur", type: "n.", definition: "One that is employed to operate a motor vehicle for the transportation of persons." },
    { word: "Chemistry", type: "n.", definition: "The science of the composition, structure, properties, and reactions of matter, especially of atomic and molecular systems." },
    { word: "Citizen", type: "n.", definition: "A person owing loyalty to and entitled by birth or naturalization to the protection of a state or nation." },
    { word: "Coalition", type: "n.", definition: "The temporary alliance of distinct parties, persons, or states to achieve a common purpose." },
    { word: "Colossal", type: "adj.", definition: "Of a size, extent, or degree that elicits awe or taxes belief; immense." },
    { word: "Column", type: "n.", definition: "A supporting pillar consisting of a base, a cylindrical shaft, and a capital." },
    { word: "Communicate", type: "v.", definition: "To convey information about; make known." },
    { word: "Compatible", type: "adj.", definition: "Capable of existing together in harmony." },
    { word: "Condemn", type: "v.", definition: "To express strong disapproval of." },
    { word: "Conductor", type: "n.", definition: "One who is in charge of a railroad train, bus, or streetcar." },
    { word: "Congruent", type: "adj.", definition: "Corresponding to or consistent with each other or with something else." },
    { word: "Consecutive", type: "adj.", definition: "Following one after the other in order." },
    { word: "Considerable", type: "adj.", definition: "Large in amount, extent, or degree." },
    { word: "Constellation", type: "n.", definition: "An arbitrary formation of stars perceived as a figure or design." },
    { word: "Constitution", type: "n.", definition: "The way in which a thing is composed or made up; makeup; composition." },
    { word: "Courier", type: "n.", definition: "One who carries messages, news, or information either with urgent haste or in accordance with a regular schedule." },
    { word: "Current", type: "adj.", definition: "Belonging to the present time." },
    { word: "Curriculum", type: "n.", definition: "The whole body of courses offered by an educational institution or one of its branches." },
    { word: "Debut", type: "n.", definition: "A first public appearance on a stage, on television, etc." },
    { word: "Decline", type: "v.", definition: "To express polite refusal." },
    { word: "Delicatessen", type: "n.", definition: "A store where ready-to-eat food products are sold." },
    { word: "Denominator", type: "n.", definition: "A shared trait." },
    { word: "Desperate", type: "adj.", definition: "Having lost all hope; despairing." },
    { word: "Diagnose", type: "v.", definition: "To identify a condition by evaluating its signs and symptoms." },
    { word: "Diary", type: "n.", definition: "A daily record, usually private, especially of the writer's own experiences, observations, feelings, attitudes." },
    { word: "Difficult", type: "adj.", definition: "Hard to understand; puzzling." },
    { word: "Dilemma", type: "n.", definition: "A situation requiring a choice between equally undesirable alternatives." },
    { word: "Dimension", type: "n.", definition: "A measurable aspect such as length or width." },
    { word: "Diploma", type: "n.", definition: "A document issued by an educational institution, such as a university, testifying that the recipient has earned a degree or has successfully completed a particular course of study." },
    { word: "Disguise", type: "v.", definition: "To change the customary dress or appearance of." },
    { word: "Dismal", type: "adj.", definition: "Marked by gloom, dejection, somberness, or depression of spirits." },
    { word: "Dolphin", type: "n.", definition: "Any of various small toothed whales with the snout more or less elongated into a beak and the neck vertebrae partially fused." },
    { word: "Domestic", type: "adj.", definition: "Relating to the household or the family." },
    { word: "Dreadful", type: "adj.", definition: "Arousing feelings of disapproval or dissatisfaction." },
    { word: "Duet", type: "n.", definition: "Performance of a musical composition or movement by two singers or two instrumentalists." },
    { word: "Durable", type: "adj.", definition: "Able to exist for a long time; lasting." },
    { word: "Dynasty", type: "n.", definition: "A succession of rulers from the same family or line." },
    { word: "Eccentric", type: "adj.", definition: "Departing from a recognized, conventional, or established norm or pattern." },
    { word: "Eclipse", type: "n.", definition: "The obscuration of one celestial body by another." },
    { word: "Ecstasy", type: "n.", definition: "Intense joy or delight." }
];
